# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - API-gatewayservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a9629672c0f9492aa0fef1c3c1d103f6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9db058937ebb438ba6caa5840c3c1718 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a9629672c0f9492aa0fef1c3c1d103f6 }}/api-gatewayservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'API-gatewayservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6b4dce90243f4811940651243bd03753 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a9629672c0f9492aa0fef1c3c1d103f6 }}/api-gatewayservice:${{ github.sha }}'